application: twidao
version: 1
runtime: python
api_version: 1

#default_expiration: "4d 5h"

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  mime_type: image/x-icon
  expiration: "999d"
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
#
# Pages
- url: /
  script: main.py
- url: /signup
  script: main.py
  login: required
- url: /setting
  script: main.py
  login: required
- url: /avatar/.*
  script: main.py
- url: /notfound
  script: main.py
- url: /status/.*
  script: main.py
- url: /favorites
  script: main.py
- url: /replies
  script: main.py
  login: required
- url: /directs
  script: main.py
  login: required
- url: /(\w+)
  script: main.py
#
# Actions
- url: /follow/.*
  script: main.py
  login: required
- url: /unfollow/.*
  script: main.py
  login: required
- url: /del/.*
  script: main.py
  login: required
- url: /fav/.*
  script: main.py
  login: required
- url: /unfav/.*
  script: main.py
  login: required
#
# Tasks requests -> /task/QUEUE_NAME/ACTION_HANDLER
- url: /task/avatar/resize
  script: task.py
  login: admin
- url: /task/tweets/push_timeline
  script: task.py
  login: admin
- url: /task/tweets/replies
  script: task.py
  login: admin
#
# API
- url: /api/status/.*
  script: api.py
#
- url: /admin/.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /.*
  script: main.py

#inbound_services:
#- xmpp_message
#- mail